In [14]:
#Write a function so that the columns of the output matrix are powers of the input vector.

#The order of the powers is determined by the increasing boolean argument. Specifically,
#when increasing is False, the i-th output column is the input vector raised element-wise
#to the power of N - i - 1.

import numpy as np


def funcArray(x,n,boolVal):

    if boolVal==False:
        print(np.vander(x,n,boolVal))
        
    else:
         print(np.vander(x,n,boolVal))
        
            
# Calling function to display matrix with increasing as TRUE and FALSE
funcArray(np.arange(1,6),3,True)


[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


In [15]:
#Write a function so that the columns of the output matrix are powers of the input vector.

#The order of the powers is determined by the increasing boolean argument. Specifically,
#when increasing is False, the i-th output column is the input vector raised element-wise
#to the power of N - i - 1.

import numpy as np


def funcArray(x,n,boolVal):

    if boolVal==False:
        print(np.vander(x,n,boolVal))
        
    else:
         print(np.vander(x,n,boolVal))
        
            
# Calling function to display matrix with increasing as TRUE and FALSE
funcArray(np.arange(1,6),3,False)


[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
